name: Android Build (Capacitor -> APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK (cmdline tools)
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" \
                     "build-tools;34.0.0" \
                     "platforms;android-34"

      - name: Install deps
        run: npm ci || npm install

      - name: Build web app
        run: npm run build

      - name: Add/Sync Capacitor Android
        run: |
          npx cap sync android

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: BespokeApp-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
      - name: Force Java 17 in Gradle
        run: |
          echo "org.gradle.java.home=/usr/lib/jvm/temurin-17-jdk-amd64" >> android/gradle.properties
