name: Android Build (Capacitor -> APK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node (Capacitor v6 requires Node 20+)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Set up JDK 21 (Capacitor Android requires Java 21 now)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Android SDK (cmdline tools)
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" \
                     "build-tools;34.0.0" \
                     "platforms;android-34"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build web app
        run: npm run build

      - name: Add/Sync Capacitor Android
        run: |
          if [ ! -d "android" ]; then
            npx cap add android
          fi
          npx cap sync android

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew --no-daemon assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: LoftyEyes-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
